Added yum-install-check.sh to catch when yum fails to install a package for us.

diff --git a/docker/oso-host-monitoring/src/build.sh.j2 b/docker/oso-host-monitoring/src/build.sh.j2
--- a/docker/oso-host-monitoring/src/build.sh.j2
+++ b/docker/oso-host-monitoring/src/build.sh.j2
@@ -1,16 +1,25 @@
 #!/bin/bash
 {{ generated_header }}
 
-set -o errexit
+# Make sure the script exits on first error
+set -e
 
-function cleanup() {
+RED="$(echo -e '\033[1;31m')"
+NORM="$(echo -e '\033[0m')"
+
+function handle_err() {
+  echo -e "\n${RED}ERROR: build script failed.${NORM}\n"
+}
+
+trap handle_err ERR
+
+function handle_cleanup() {
   echo -n "Removing the fingerprint... "
   [ -f ${container_fingerprint} ] && rm -f "${container_fingerprint}"
   echo "Done."
 }
 
-trap 'exit $?' ERR
-trap cleanup  INT TERM EXIT
+trap handle_cleanup  INT TERM EXIT
 
 sudo echo -e "\nTesting sudo works...\n"
 
@@ -21,16 +30,12 @@ cd $(dirname $0)
 container_fingerprint='./container-build-env-fingerprint.output'
 ./container-build-env-fingerprint.sh > ${container_fingerprint}
 
-## Make sure base is built with latest changes since we depend on it.
-# commenting this out for now because ops-base does a full rebuild everytime
-#if ../oso-rhel7-ops-base/build.sh ; then
-  # Build ourselves
-  echo
-  echo "Building oso-{{ base_os }}-host-monitoring..."
+# Build ourselves
+echo
+echo "Building oso-{{ base_os }}-host-monitoring..."
 {% if base_os == "rhel7" %}
-  sudo time docker build $@ -t oso-rhel7-host-monitoring .
+sudo time docker build $@ -t oso-rhel7-host-monitoring .
 {% elif base_os == "centos7" %}
-  sudo time docker build $@ -t oso-centos7-host-monitoring . && \
-  sudo docker tag oso-centos7-host-monitoring openshifttools/oso-centos7-host-monitoring:latest
+sudo time docker build $@ -t oso-centos7-host-monitoring .
+sudo docker tag oso-centos7-host-monitoring openshifttools/oso-centos7-host-monitoring:latest
 {% endif %}
-#fi
diff --git a/docker/oso-zaio/src/build.sh.j2 b/docker/oso-zaio/src/build.sh.j2
--- a/docker/oso-zaio/src/build.sh.j2
+++ b/docker/oso-zaio/src/build.sh.j2
@@ -1,5 +1,17 @@
-#!/bin/bash -e
+#!/bin/bash
 {{ generated_header }}
+
+# Make sure the script exits on first error
+set -e
+
+RED="$(echo -e '\033[1;31m')"
+NORM="$(echo -e '\033[0m')"
+
+function handle_err() {
+  echo -e "\n${RED}ERROR: build script failed.${NORM}\n"
+}
+
+trap handle_err ERR
 
 sudo echo -e "\nTesting sudo works...\n"
 
@@ -7,6 +19,6 @@ cd $(dirname $0)
 {% if base_os == "rhel7" %}
 sudo time docker build $@ -t oso-rhel7-zaio .
 {% elif base_os == "centos7" %}
-sudo time docker build $@ -t oso-centos7-zaio . && \
+sudo time docker build $@ -t oso-centos7-zaio .
 sudo docker tag oso-centos7-zaio openshifttools/oso-centos7-zaio:latest
 {% endif %}
